export const AUTH = "AUTH";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOAD_USER = "LOAD_USER";
export const LOAD_ERROR = "LOAD_ERROR";

export const LOGOUT = "LOGOUT";

export const MOVIES_LOADING = "MOVIES_LOADING";
export const MOVIES_LOADED = "MOVIES_LOADED";
export const MOVIES_ERROR = "MOVIES_ERROR";

export const SERIES_LOADING = "SERIES_LOADING";
export const SERIES_LOADED = "SERIES_LOADED";
export const SERIES_ERROR = "SERIES_ERROR";

export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";
export const ADD_MOVIE_LOADED = "ADD_MOVIE_LOADED";
export const ADD_MOVIE_LOADING = "ADD_MOVIE_LOADING";

export const DELETE_MOVIE_ERROR = "DELETE_MOVIE_ERROR";
export const DELETE_MOVIE_LOADED = "DELETE_MOVIE_LOADED";
export const DELETE_MOVIE_LOADING = "DELETE_MOVIE_LOADING";

export const ADD_SERIES_ERROR = "ADD_SERIES_ERROR";
export const ADD_SERIES_LOADED = "ADD_SERIES_LOADED";
export const ADD_SERIES_LOADING = "ADD_SERIES_LOADING";

export const DELETE_SERIES_ERROR = "DELETE_SERIES_ERROR";
export const DELETE_SERIES_LOADED = "DELETE_SERIES_LOADED";
export const DELETE_SERIES_LOADING = "DELETE_SERIES_LOADING";
